### ISSUE TITLE
Audio is not recording on MacOS Ventura

### ISSUE THREAD

**Issue by sethw8** [wulkano/kap#1154]
**macOS version:**    Ventura (13)
**Kap version:**      3.5.5

**Comment by timothyis** [comment]
Hi @sethw8. Thanks for submitting an issue.

I'd appreciate if you could fill in the issue template as this is there for us to understand your problem further.  Which audio are you expecting to hear? Are you getting no audio whatsoever? Have you granted the correct permissions? Is it disabled in your settings? 

Kap also has a newer version than 3.5.5, so please try updating and see if this fixes your issue.

Since this issue doesn't have the information we need, I'll close it for now.

**Comment by inglesuniversal** [comment]
Which audio recording free plugin can be used with iOS Ventura on M2 MacBook?  Thanks
