### ISSUE TITLE
Why is Kap asking for permission to access local servers?

### ISSUE THREAD

**Issue by sifex** [wulkano/kap#130]
When I open Kap, or press that crop button, Kap is opening a dialog (5 times) to login to local servers. 
This is most likely as a result of favouriting those servers in Finder.

**Platform**: MacOS 10.12.1
**Kap Version**: 1.0.0 (10.0.0.134)
**Steps to reproduce**: Open Kap with Servers currently disconnected in Finder Sidebar Section – "Favourites"
**Current behaviour**: Kap opens permission dialog (5 times) to access favourited servers not currently connected.
**Expected behaviour**: Don't ask to access personal server, or ask permission for unnecessary network locations.
**Workaround**: N/A (Unable to use app)

Screenshot:
![screen shot 2017-01-12 at 12 53 54 pm](https://cloud.githubusercontent.com/assets/2058557/21874046/9b6492f4-d8c6-11e6-819d-61d1b23248b2.png)

**Comment by skllcrn** [comment]
That doesn't sound like much fun, I'm sorry! Have you had this issue in other applications? Is Kap located on the same HD as your OS, or on an external disk?

**Comment by sifex** [comment]
Nup, Kap is in /Applications/, and not on an external disk.

**Comment by skllcrn** [comment]
It's really weird, it's not something we're purposefully asking for. Do you have this issue in other Electron apps, Atom, for example?

**Comment by sifex** [comment]
It's happened with one other electron app before, wasn't Atom though.

The issue has disappeared. Worth investigating if someone else has the issue.

**Comment by doot0** [comment]
If the issue was also present in another Electron app I'm guessing the issue is upstream.

I'm on mobile right now so I can't check myself, but are there any issues describing this behaviour on the Electron repo?

**Comment by t-ack3** [comment]
This started happening recently on one of our editing machines as well except it throws the following error: "There was a problem connecting to the server "xxxxx". The server may not exist or it is unavailable at this time. Check the server name or IP address, check your network connection, and try again"

This only happens when you click the Crop button which then doesn't allow you to ever record.

<img width="532" alt="screen shot 2017-11-02 at 5 08 06 pm" src="https://user-images.githubusercontent.com/32207002/32352795-b801f16a-bff0-11e7-8f15-8604201057ef.png">

**Comment by sindresorhus** [comment]
@t-ack3 @sifex Please test the latest Kap beta: https://kap-beta-updates.now.sh A lot has changed since v1.
