### ISSUE TITLE
Export as GIF

### ISSUE THREAD

**Issue by rgbkrk** [wulkano/kap#14]
Many times I end up wanting to export directly to a GIF instead of MP4. Would it be in scope for this project to export to GIF (likely as a follow on transform of the MP4?)

**Comment by matheuss** [comment]
It's in our plans since the beginning, @rgbkrk! We're working on this and it will be available soon! Thanks for the issue 😄

**Comment by GottZ** [comment]
the following is just a suggestion:
try to record uncompressed if gif is selected. in most cases it would make a big difference in output size due to how gif works. (i know the gif spec quite well)
![image](https://cloud.githubusercontent.com/assets/559564/19443313/9e992daa-948c-11e6-9cf7-cdb52b41aba2.png)

**Comment by skllcrn** [comment]
I'm just here to say that your website is marvellous, @GottZ.

**Comment by CodeTheory** [comment]
Exporting as GIF was released today!

If you haven't downloaded Kap already, download the latest [here](https://getkap.co/download)! (read the [changelog](https://getkap.co/releases/gif)).

If you've already downloaded Kap and have it open, you should have received an auto-update notification already, so just click it!

Thanks, everyone. ❤️
