### ISSUE TITLE
Automatic share to iCloud

### ISSUE THREAD

**Issue by Slauta** [wulkano/kap#166]
Hi,

Very useful functionality, so that after saving the record is automatically scrolled and the link is copied to the clipboard.

Is such a functional planned?

**Comment by sindresorhus** [comment]
> the record is automatically scrolled

What does this mean?

**Comment by sindresorhus** [comment]
I'm not sure iCloud provides the functionality of creating public link for files. If so, it could be solved with a plugin when we implement the plugin functionality.

**Comment by Slauta** [comment]
Ok, what if Dropbox, OneDrive, Yandex.Disk this functional is present.

**Comment by CodeTheory** [comment]
@Slauta Do you mean "If Dropbox is present, share to Dropbox"? Otherwise I don't understand.

**Comment by Slauta** [comment]
@CodeTheory Yes!)

**Comment by CodeTheory** [comment]
In this case we already have an issue open for such a thing 😄 #147 

We're working on plugins, as @sindresorhus mentioned; this should enable us or others to create functionality just as you requested.

Since we already have a few issues open related to this, I'm going to go ahead and closed this one. Thanks for your request, though!

**Comment by Slauta** [comment]
Cool! 👍
