### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by jadbox** [wulkano/kap#20]
Please? ;)

What's the level of effort- is there Mac only extensions/libs being used with Electron?

**Comment by CodeTheory** [comment]
I don't believe we're using Mac specific libs (can you concur @matheuss?). None of us have Windows is all. We fully want to support other OS's. Pull requests welcome!

**Comment by maxlath** [comment]
was about to open the same issue for Linux: yep, cross-platform would be awesome :)

**Comment by dmitry** [comment]
I think it's better to open separate issue for linux.

**Comment by madcampos** [comment]
Doesn't electron's [`desktopCapturer`](http://electron.atom.io/docs/api/desktop-capturer/) api supply the methods needed?
I think it's almost like what is used for webrtc or something like that.

**Comment by doot0** [comment]
@madcampos It does, but the performance is does not meet the standards we want to deliver. We experimented with it early on but we couldn't glean a decent FPS from the capturer API, hence why we opted to write a native library with AVFoundation and use that instead.

**Comment by madcampos** [comment]
What are the performance problems?
Maybe we can workout something, if it's more performant on windows there can be a option to use the native library on one platform and the electron builtin on another, or offer it as a fallback even with performance hits while a native addon is in the works.

**Comment by matheuss** [comment]
@madcampos I'm busy right now but I don't want to leave you without an answer, so I'm giving a quick one:

We tried the UserMedia API for several days and it turned out to be very shitty: we had an average of ~15 fps when recording the whole screen and it used a **lot** of CPU for that. So then we moved to `ffmpeg`, which can record just fine, but also uses a lot (less than UserMedia) of CPU. 

So we decided to go native. It's the hardest path, but the best in terms of performance – based on our experience 😄 

See `aperture.js`' `Why` section for more info: [`aperture.js#why`](https://github.com/wulkano/aperture.js#why)

**Comment by doot0** [comment]
To expand a little;

We've actually discussed this internally for a little while. We have explored using `ffmpeg` as a cross-platform fallback but the CPU usage has shown to be **extremely** costly [(see here for comparison)](https://github.com/wulkano/aperture.js#why). Additionally, in order to meet our ideal performance margins we would need to tweak performance for `ffmpeg` on a per-system basis, which would probably be pretty complex. 🤔

**Comment by levrik** [comment]
OBS is doing some screen capturing on Windows. I thing the code is located here: https://github.com/jp9000/obs-studio/tree/master/plugins/win-capture
But I don't know how the CPU usage is and if this is helpful.

**Comment by PaulBGD** [comment]
After I'm finished with #37 I'll look into getting this working on Linux. Most of the work separating OS code is done in #37 so this shouldn't be too hard.

**Comment by ikourfaln** [comment]
+1

**Comment by aredfox** [comment]
+1
I noticed desktopCapturer is indeed a pitfall and too slow, it (calling .getSources()) also freezes electron UI/process for a brief moment (even when using proper callbacks etc) - on all platforms. Since I feel the API that comes with electron really underdelivers, I posted this as an issue on electron/electron https://github.com/electron/electron/issues/8246.

**Comment by madcampos** [comment]
From what I've been prospecting, it's an issue within chromium.
For windows, the native methods relay on basically 3 apis:
1. GDI - witch is somewhat slow depending on the size of the screen and the codec been used, I tested it with ffmpeg (it's their default method)
2. DirectX - from what I read, it can be fast but is a little harder to implement/depend on more libs/versions witch can lead to dll hell
3. WinRT (universal platform api) - it's shinny and new, meaning it will be win 8+ but seems easy to implement.

The problem i got with ffmpeg was frame drop on the recording, some combinations of apis + codecs barely got 30fps. And that is a problem also, encoding to something other than AVI will be a question of post-processing the video.

**Comment by PaulBGD** [comment]
@madcampos Did you make sure to enable GPU encoding with ffmpeg?

**Comment by madcampos** [comment]
@PaulBGD I think no, it wasn't enabled... I don't think there is an option with the pre-compiled binaries (the one I'm using)

**Comment by db2k** [comment]
Maybe we could use this library for recording the screen?
https://github.com/wulkano/aperture.js

**Comment by db2k** [comment]
wow nevermind... I just saw it's written by you too. :D I'll try to get it working on Windows somehow.

**Comment by grahamperrin** [comment]
_Multi-platform_ https://github.com/wulkano/kap/issues/123 was closed in favour of this issue 20 so I'll express an interest in use on FreeBSD-based TrueOS Desktop. Related: https://github.com/electron/electron/issues/3797

**Comment by Jbithell** [comment]
+1 for Windows support

**Comment by doot0** [comment]
Commenting "+1" doesn't achieve anything. This is why github introduced emoji reactions to comments. Please refrain from commenting "+1".

**Comment by MarkTiedemann** [comment]
@doot0 I think the main reason why people still +1 instead of using emojis is that this feature isn't available on the mobile yet.

I know it's a bit annoying, but for the sake of not excluding mobile users, I suggest accepting +1s in that case. :)

**Comment by matheuss** [comment]
-1

**Comment by Jbithell** [comment]
@doot0 er thanks for the tip(!) - clearly I touched a nerve...
It's a practical thing I'm afraid - I think "+1" is a quick and easy way to comment your support for an issue that clearly isn't getting much traction (because of considerably technical challenges, which I totally appreciate) on mobile - where you can't even see the reactions of others, let alone give your reaction.

**Comment by matheuss** [comment]
@Jbithell -1

**Comment by vogon101** [comment]
I agree with @doot0. Simply commenting "+1" is superfluous and even when on mobile. To be more useful perhaps expand on why you would like the feature.

**Comment by Jbithell** [comment]
I'd like it on Windows because it looks like a really cool piece of software, Macs are prohibitively expensive, and Windows has been crying out for this kind of thing for a long time. 
But the kind of time we're spending on whether I should have posted those fateful two characters `"+1" ` is perhaps a sign that it's not to be...

**Comment by matheuss** [comment]
Actually commenting `+1` adds one useless notification to the ~100 that appeared on my github.com/notifications just today 😐

If someone has any useful info/idea/etc about how to port Kap to Windows, please ping me on https://twitter.com/matheusfrndes. I'll be more than happy to allow comments here again, since now I'm interested on such feature – wasn't before.

**Comment by Torbilicious** [comment]
I am not very much in the topic of capturing/encoding, but would the [nvidia capture sdk](https://developer.nvidia.com/capture-sdk) be an option?

**Comment by albinekb** [comment]
@Torbilicious The biggest issue is not how to do it, we need to find a windows developer up to the task of maintaining windows support, see https://github.com/wulkano/kap/issues/270#issuecomment-340598274

**Comment by Fydon** [comment]
@Torbilicious The issue with the Nvidia Capture SDK is that it requires Nvidia hardware. I have Nvidia hardware, but not everyone does.

**Comment by Torbilicious** [comment]
@Fydon that is correct but I would prefer an Nvidia only windows version over no windows version.
But I sadly much dislike c++ and the general hardware close Codestyle so I don't think I could maintain this...

**Comment by albinekb** [comment]
The best would be to use Nvidia if there's hardware present 👍  But that will most likely be very intensive to do and later maintain.

**Comment by AluminiumTech** [comment]
Could FFMPEG support be added for Windows in Aperture?

Cos using Graphics Acceleration to record it provides far better framerate. E.g. using Intel QuickSync H.264 on Intel iGPUs.

OBS Studio does this as well as NVENC support (on Nvidia dGPUs)and AMD's GPU accelerated codec support so it's clearly possible.

**Comment by benfavre** [comment]
Open source software for Mac only always makes me laugh. Just WTF

**Comment by skllcrn** [comment]
See https://github.com/wulkano/aperture#why and https://github.com/wulkano/aperture/issues/30#issuecomment-280979505. Closing in favour of #456.
