### ISSUE TITLE
VLC/MPlayerX playback fails

### ISSUE THREAD

**Issue by bramkok** [wulkano/kap#22]
Playback of Kap Version 0.1.0 (0.1.0.14) recordings on macOS 10.12 using VLC Version 2.2.4 Weatherwax (Intel 64bit) or MPlayerX Version 1.1.4 (1920) results in a beachball of death.

However, using QuickTime the recordings can be viewed without error.

**Comment by CodeTheory** [comment]
Can reproduce. Looking into it.

**Comment by matheuss** [comment]
@bramkok could you see if you can reproduce it with a recording from QuickTime?

**Comment by bramkok** [comment]
Can't reproduce this behavior with QuickTime screen recording.

[QuickTime screen recording test](https://vimeo.com/185732939)
[MPlayerX playback test](https://vimeo.com/185732938)
[VLC playback test](https://vimeo.com/185732937)

^ all recorded with Kap.

**Comment by matheuss** [comment]
Thank you for the detailed feedback @bramkok 😌 We'll be shipping a fix with the release that's coming tomorrow! 😄

**Comment by matheuss** [comment]
Well, sadly we could not find a viable solution for this 😔 

It's a pretty weird _bug_ – you can play the Kaptures on Chrome and QuickTime, for example, with no problems 😕 

We spend some time yesterday researching about this and here's what we found:

### Info about a Kapture via `ffprobe file.mp4`

`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1016x1016 [SAR 1:1 DAR 1:1], 50 kb/s, 30 fps, 30 tbr, 6k tbn, 50 tbc (default)`

### Info about a QuickTime recording via `ffprobe file.mp4`

`Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1216x872 [SAR 1:1 DAR 152:109], 113 kb/s, 60 fps, 60 tbr, 6k tbn, 50 tbc (default)`

Notice that they are almost the same – the only difference is the profile name (`High` vs `Main`).

## Fixing it

`ffmpeg -i Kapture.mp4 -pix_fmt yuv420p -preset ultrafast Kapture-fixed.mp4`

This will change the `ffprobe` output to:

`Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1016x1016 [SAR 1:1 DAR 1:1], 25 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)`

Notice that the `(tv, bt709)` is gone.

This is enough to make VLC open the file without trouble.

## Fixing it with Swift

We could also fix it low level – you can choose the pixel format when recording with `AVFoundation`. There's some _(rare)_ info about that out there, like [this article](https://www.invasivecode.com/weblog/AVFoundation-Swift-capture-video/). It's a hard task and I'm afraid we don't have time for it now 😔 We want to focus on features like GIF support (#14) and `kap-server` (#23).

## Conclusion

We'd like to add it to [`aperture.js`](https://github.com/wulkano/aperture), but the problem is: it can add a lot of post processing time to a Kapture. With small ones (~500x500), it's ok; with bigger ones (3000x1800 for instance) it takes something like 3 seconds for each second of video (tested in a MacBook Pro Retina 13" Mid 2014) 😕 

For now, I would like to classify this as a _kinda_ `upstream` issue, since Chrome, Slack, QuickTime etc have no problem to play Kaptures.

## **Any help with this is more than welcome!**
