### ISSUE TITLE
How do I give you money?

### ISSUE THREAD

**Issue by amirrajan** [wulkano/kap#227]
Love this damn tool. How do I give money to this project?

**Comment by CodeTheory** [comment]
Hi @amirrajan! I'm really happy that you like Kap this much, but we really don't want money for it! 

Kap is a passion product for us. We made it because we wanted it ourselves and knew we weren't alone. 

If you are willing to give up some money in support of Kap, what we'd _really_ love is if you could put that money towards people much more deserving and in-need of it than ourselves.
If you want some ideas on where that money could do good, we suggest investing in the future of tech to keep projects like Kap popping up! http://www.blackgirlscode.com/ is brilliant for this!
Otherwise, with the natural disasters lately, any money there could really be beneficial to many people.

We'll keep on working on Kap (we have v2 in the works, which you can test at kap-artifacts.now.sh/master) in our spare time, even without donations 🎉 

Again, _really_, thank you for the consideration. We hope you enjoy our upcoming updates ❤️

**Comment by amirrajan** [comment]
![image](https://user-images.githubusercontent.com/517055/30235112-373bc642-94ca-11e7-97ab-a3168d1a8ae4.png)

Done.

**Comment by CodeTheory** [comment]
You are amazing! On behalf of the team, I can't thank you enough for that! ❤️

**Comment by CodeTheory** [comment]
I'm going to leave this issue open, just in-case any should find it and feel compelled to act in a similar manner! Thank you, again. 😊

**Comment by CodeTheory** [comment]
Turning this into an issue for adding a section to the readme for why we don't want money
