### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by pudgereyem** [wulkano/kap#32]
Hey guys, nice work!
However, I didn't find it very performant (read: low fps).

I did an example where you can see the difference between _kap_, and _Quicktime Screen Recording_, see below:
- [Capture with Quicktime](http://pudge.se/P3Gd) (.mov, 5s long, 875kb)
- [Captured with Kap](http://pudge.se/yCk3) (.mp4, 5s long, 909kb)

As you can see the file recorded with Kap also weighs more.

**Comment by doot0** [comment]
Hey @pudgereyem, thanks for your feedback! 

Kap records at (currently hardcoded) 30FPS. We should add the ability to toggle between 30/60. 

Solving this issue is a bit more complicated than just changing a variable, as the FPS is defined by [one of the dependencies](https://github.com/wulkano/aperture/) we're using. We'll have to make updates to that first, then put together a way to change it in the UI. cc @matheuss 

Regarding heavy file-sizes, we currently don't compress any video recorded with Kap. We chose 30FPS & no compression originally because it was the best value for quality and filesize (60FPS would be a little under double of course). Apple have an advantage over us because .mov is a format they authored so no doubt they're able to do some cool tricks under the hood that we're not able to 😉.

This is an issue we can solve down the line by providing an option to change these things in the upcoming preferences pane feature we're working on.

**Comment by pudgereyem** [comment]
Hey @doot0!

> Solving this issue is a bit more complicated than just changing a variable, as the FPS is defined by one of the dependencies we're using. We'll have to make updates to that first, then put together a way to change it in the UI. cc @matheuss

Could you not simply set it as you do with `cropArea`, when calling `aperture.startRecording`?
[Your code here](https://github.com/wulkano/kap/blob/f7d4e39a69d24fd9972ef35489a2963c87006f5a/app/src/renderer/js/index.js#L104). Checked the dependency and it seems to me that `fps` is a option, [see here](https://github.com/wulkano/aperture/blob/ef5f9ac83560fcc413e49779e84b6c080c527f9b/index.js#L25).

**Comment by doot0** [comment]
@pudgereyem Hahah oh boy, you'll have to forgive me - I haven't had any coffee yet. 😅 

In that case, let me put this On Hold for now until I can get some more feedback from the team. No doubt they'll wanna add an option to configure this. 👍

**Comment by pudgereyem** [comment]
@doot0 haha, no worries. I pulled down the repo and changed it, but didn't see any increase in performance though. Don't have time to look more into it right now.

We all want those 60 frames per second, I'd label it `Priority: MEGA` ;D

**Comment by doot0** [comment]
@pudgereyem I'll bump it to medium, just for you. 😜

**Comment by matheuss** [comment]
Done ✨ 
![screen shot 2016-12-12 at 7 46 45 am](https://cloud.githubusercontent.com/assets/4721750/21094667/2bc33062-c03f-11e6-8987-1f5c603c8e47.png)
