### ISSUE TITLE
Blacklist redundant apps from the window selector

### ISSUE THREAD

**Issue by onordbo** [wulkano/kap#327]
**Platform:** MacOS
**Kap Version:** 2.0.0-beta.4 (2.0.0-beta.4.556)
### Steps to reproduce
Currently, a vast amount of redundant apps show up in the window selector that are currently not recordable.

### Suggested fix
Create a blacklist of known redundant apps that shouldn't show up in the menu.

**Comment by sindresorhus** [comment]
@onordbo Can you include the screenshot you shared on Slack? Just so we remember which apps were needlessly included?

**Comment by sindresorhus** [comment]
Are anyone else experiencing this?

**Comment by sindresorhus** [comment]
And as commented in Slack. This should really be an issue on https://github.com/karaggeorge/mac-windows

**Comment by onordbo** [comment]
![image](https://user-images.githubusercontent.com/4263132/34819019-d8f85f32-f6bc-11e7-8b13-95a5dfcfe63d.png)

**Comment by sindresorhus** [comment]
// @karaggeorge

**Comment by sallar** [comment]
@sindresorhus From the code it seems that the package should return only elements that are on screen... not sure why its returning all that.. 
https://github.com/karaggeorge/mac-windows/blob/a45d47e00af1fc32fca0539a7936290128302c30/index.js#L39
@karaggeorge

**Comment by karaggeorge** [comment]
I have no idea how I missed this. I don't remember getting a notification for it. There are no options for the Quartz Swift package to exclude the menubar icons as windows. I noticed that they all had position `y = 0` (attached to the top), so as a hacky solution I was filtering against that and it seemed to be working fine. Since it obviously is not a general rule, I tried a different approach. The API says that the windows are returned in order from front to back, and all the menu bar icons seem to be in front of a process called "Menubar", while the rest of the apps are behind it. So, as a (hopefully) improved filter, I slice anything that is in front of "Menubar" including that. For me, it's the same result. Hopefully @onordbo can pull the branch and test if that solves the problem in his case

(https://github.com/wulkano/kap/pull/403 updated the dependency)
