### ISSUE TITLE
Use HEVC instead of H264

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#341]
We can't do for now, as Chrome doesn't yet support it, and they have no plans to support it yet. Just opening this issue so we can do it eventually.

**Comment by skllcrn** [comment]
Related:

https://github.com/wulkano/kap/issues/220#issuecomment-359052563

For now we're discussing generating a low-res preview video using `ffmpeg` for the editor. We already support exporting HEVC because `ffmpeg` supports it, for the preview we can use its fast mode. 

https://stackoverflow.com/questions/39473434/ffmpeg-command-for-faster-encoding-at-a-decent-bitrate-with-smaller-file-size

At the very least we should handle HEVC imports with an error message.
