### ISSUE TITLE
Kap offers unsupported update

### ISSUE THREAD

**Issue by tomscholz** [wulkano/kap#367]
**Platform:** OS X 10.11.6 (El Capitan)
**Kap Version:** 1.0.1 (1.0.1.170)
Kap offers me to update to a newer version that isn't supported by El Capitan.
![skjermbilde 2018-02-01 kl 18 18 09](https://user-images.githubusercontent.com/20381749/35692696-4d902008-077c-11e8-90ef-96579d8f7571.png). 

### Expected behavior
Kap shouldn't offer users to update to a not compatible version.
### Workaround
Check if the current OS version is compatible with the newer version of Kap

**Comment by albinekb** [comment]
Thanks for reporting this! Unfortunately there's no way to fix this without requiring significant effort, that effort is better focused on supporting the latest OS and working on fixing features that will benefit our upgrading users. Not worth the effort needed to fix this IMHO. Upgrade your OS. 👍

**Comment by tomscholz** [comment]
@albinekb Haha ok. I understand. 
> Upgrade your OS. 👍

naaaah. I'm fine with el capitan ;)

**Comment by albinekb** [comment]
Thank you for understanding 🙏😊 I urge you to upgrade, the new Kap is amazing. 👌😉

**Comment by justsml** [comment]
Is there an option to disable checking for updates in v1?

I'm running `El Capitan v10.11.6 (15G17023)` and it does the forced upgrade - which breaks Kap every time I reboot. 
It's a pain in the ass to re-install the old version so often. 😿 

### I promise I'm not just a complainer, if someone can point me in the right direction, *I'd love to submit a PR.*

**Comment by albinekb** [comment]
@justsml thanks for that, but we do not want to add an option to stop updates, we don't want people to stay on old versions, because it will be hell to maintain. 

What I suggest you doing, I can help you if you want - is to build your own old version from source.  Would that be an ok workaround for you? I can even build and upload it for you if you want. Thanks for understanding 🙏♥️

**Comment by yamsellem** [comment]
@albinekb may you consider adding an option to stop updates /only/ on release 1.0.1? (1.0.1.2 maybe)

Some of us are blocked on El Captain (mid 2011 macs, for exemple — which still works amazingly well), each time we use kap, we need to delete the forced update to 2.0 and download again 1.0.

Offering an autoupdate is nice, forcing users to get non compatible updates can be disappointing in the long run. Thanks a lot.

**Comment by skllcrn** [comment]
We don't have the resources to support old releases @yamsellem, which means we won't be releasing any patches for v2.2.0 or before. Additionally, official support for Kap is limited to macOS 10.12 or never. This isn't the answer you were hoping for, but I hope you can understand our need to ruthlessly prioritise in order to get the best Kap to as many people as possible. 

Your best best is to apply the workaround @albinekb suggested above: 

> What I suggest you to do is to block `kap-updates.now.sh` in your firewall/hosts file, here's how to do it https://www.wikihow.com/Block-a-Website-on-Mac

**Comment by yamsellem** [comment]
@skllcrn I completely understand your priorities & editing `/etc/hosts` is perfectly fine to me.
Thanks for your quick solution to the issue — autoupdates are not fetched anymore on 1.0.1, perfect!

**Comment by albinekb** [comment]
Glad that it helped @yamsellem! I think you can get Mojave running on your 2011 mac if you'd like, see this video: https://www.youtube.com/watch?v=ZLVvP3WCCI0
