### ISSUE TITLE
Readme link downloads v1 instead of v2

### ISSUE THREAD

**Issue by vladikoff** [wulkano/kap#376]
Clicking on `Download the latest release (macOS only)` in the readme goes to https://getkap.co/download and for me that downloads release v1.

![image](https://user-images.githubusercontent.com/128755/35745147-34c73d7e-0810-11e8-97a0-71feefddc732.png)

But even the main site now has 2.0.0 via https://getkap.co/

Sorry if this was already filed, I searched a bit!

**Comment by skllcrn** [comment]
Normally https://getkap.co/download will grab the latest, but we're having some issues with the server that deals with that. Should be fixed soon!

**Comment by matheuss** [comment]
Fixed! I can't remember why but we have the download link hardcoded server side. Besides that, it was redirecting with HTTP 301, which shouldn't be the case. I changed to 302 👍 

Note that your browser will have the redirection cached since we were returning HTTP 301, so please try on an anonymous tab 🙏
