### ISSUE TITLE
Sometimes, video files encode at unneccessarily high bitrate

### ISSUE THREAD

**Issue by nateberkopec** [wulkano/kap#43]
Example capture, encoded at average 1426 kb/s:

[Kapture 2016-10-10 at 13.01.36.mp4.zip](https://github.com/wulkano/kap/files/520234/Kapture.2016-10-10.at.13.01.36.mp4.zip)

Running this through `ffmpeg -i Kapture\ 2016-10-10\ at\ 13.01.36.mp4 -vcodec h264 -strict -2 output.mp4` results in a bitrate of ~204kb/s. 

Might just be because of the video type (mostly static with 1 small motion region).

**Comment by matheuss** [comment]
Thanks for the report, @nateberkopec! This is happening because [aperture.js](https://github.com/wulkano/aperture.js) records an uncompressed movie.

We had a `compression` option in an early version, but we decided to disable it at some point to focus on other things first.

I'm currently working on #14 for [`v0.3.0`](https://github.com/wulkano/kap/milestone/1) and I think we could have the `compression` option back in [`v0.3.0`](https://github.com/wulkano/kap/milestone/3) 😄

**Comment by skllcrn** [comment]
Related to #117

**Comment by skllcrn** [comment]
Closing this as I t doesn’t really make sense to capture the MP4 source file at a lower bitrate.
