### ISSUE TITLE
Can not save recording on macOS 10.15 Beta

### ISSUE THREAD

**Issue by iRoachie** [wulkano/kap#682]
**macOS version:** 10.15 Beta
**Kap version:** 2.2.0

#### Steps to reproduce
Click to record, start recording, stop recording

#### Current behaviour
Errors right after clicking stop

#### Expected behaviour
Video preview window should show

#### Workaround
No workaround

#### Attached Error
```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture {"destination":"file:///private/var/folders/dk/09cf0qrx77q6rwxq6hlb0nmr0000gn/T/a2feb666f7c405c49ed2550c3e7a19a1.mp4","fps":60,"showCursor":true,"highlightClicks":true,"displayId":"69733382","cropRect":[[62,337],[411,753]]}
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={AVErrorRecordingSuccessfullyFinishedKey=false, NSLocalizedDescription=The operation could not be completed, NSLocalizedFailureReason=An unknown error occurred (-16345), NSURL=file:///private/var/folders/dk/09cf0qrx77q6rwxq6hlb0nmr0000gn/T/a2feb666f7c405c49ed2550c3e7a19a1.mp4, NSUnderlyingError=0x7ff7ded2b320 {Error Domain=NSOSStatusErrorDomain Code=-16345 "(null)"}}
FigMovieFormatFileWriter::PostProcessMovie: WriteMovie() errored!!! -16345
    at Promise.all.then.arr (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:236:11)
    at <anonymous>
```

**Comment by skllcrn** [comment]
This looks like an issue with config and/or permissions to me, what do you think @sindresorhus?

**Comment by franciscop-sc** [comment]
Seeing exactly the same error after upgrading to *10.15 beta*, please let me know if I can help debugging this somehow.

**Comment by sindresorhus** [comment]
I don't have time to debug Kap v2 stuff. I will look into it further if you can reproduce with the v3 beta: https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.5

**Comment by franciscop-sc** [comment]
I tried the new beta. A popup stating something along the lines of "couldn't start recording within 5 seconds" showed up. Then the real issue came, since it seems like it crashed and locked the screen in the "recording" state and didn't allow to quit it anyhow. Clicking the bar icon did not show or do anything, the screen remained like this until I rebooted:

<img width="920" alt="Screen Shot 2019-06-17 at 12 13 39" src="https://user-images.githubusercontent.com/47550791/59576981-b25b5880-90fc-11e9-8cef-b475fc513cf9.png">

After the restart it doesn't crash anymore. When clicking it the new menu appears, it seems to start recording with the bar button changing. But after pressing the "Stop" the whole thing just disappears and no file is generated, there's no popup and the specified saving folder does not contain any new file.

**Comment by NSExceptional** [comment]
@sindresorhus I get a dialog that says "The application Kap Beta can't be opened" using beta 5 on Catalina B2.

**Comment by kalkih** [comment]
Same as above using Catalina B2 with Kap 3 beta 5, also seems like the dark screen overlay get stuck after the error pops up, had to force close the app to get rid of it.

**Comment by mrmos** [comment]
I was able to fix this by doing

System Preferences > Security & Privacy > Re-select Kap in list of Apps

![image](https://user-images.githubusercontent.com/37348735/61751410-135df800-ad5d-11e9-8261-40e869307a43.png)

**Comment by franciscop-sc** [comment]
In the latest Catalina it was fixed for me as well. I _believe_ I might have done what @mrmos is suggesting accidentally (+a couple of restart cycles), deselected all the "screen recordings" and selected them again, and now both Kap and Kap Beta works.
