### ISSUE TITLE
Temp files not deleted when video preview is closed

### ISSUE THREAD

**Issue by someone857** [wulkano/Kap#762]
**macOS version:**
10.15

**Kap version:**
3.0.0

#### Steps to reproduce

1. Record a video
2. save it or not
3. close the preview window
4. open your temp folder (/private/var/folders/yy/xxxxxxxxxxxx/T/)

#### Current behaviour
The video is still on the temp folder (root above) as well as on subfolders with the exported format.

#### Expected behaviour
Remove the temp files when the video is discarded. We're talking about videos that could easily grow to Gb, and mostly Mac users don't restart their computer often enough to trigger the cleaning process

#### Workaround
Access the temp folder and delete the files manually

**Comment by faxotherapy** [comment]
I was myself a bit surprise to see how much space left I had after using the app reliably four times: 31 Gigs for a group of 4 recordings located at `/private/var/folders/6c/f45g67fx61z0qbyxgjl_hqf40000gp/T`

**Comment by karaggeorge** [comment]
Maybe an icon on the exports window to delete? Or another action in the dropdown when you click on the icon?

Or an option in the preferences, that says delete recordings after [...] with an option for never?

**Comment by skllcrn** [comment]
Another action in the dropdown to remove it from the history (and the cache) sounds like a reasonable addition to me @karaggeorge. Is there any other measure we could take during the session, like adding some sort of a threshold for the cache?

**Comment by karaggeorge** [comment]
We could check every x minutes and delete them. Will be harder if they editor for that recording is still open.

I'm not sure enabling it by default is the best though, since your recordings would start disappearing from the editor, which is something we haven't done before. I personally wouldn't like this feature.

That's why I said, maybe have a preference for it if we go that route

**Comment by skllcrn** [comment]
Adding a menu item to clear them also sounds good, something like "Clear Export History", I think. I suggest we stick to that and adding another option in the context menu for now, before we look more at adding additional logic or settings to handle it.

**Comment by gotjoshua** [comment]
Are there any plans to make the tmp folder configurable? i can't afford that amount of space on my OS drive... Should I open another issue about that?

**Comment by frozenpandaman** [comment]
> Are there any plans to make the tmp folder configurable? i can't afford that amount of space on my OS drive...

I'd like this as well, but in the other direction, or for other reasons – recordings seem to mess up often enough that I'd like easier manual access to this folder an have it not be garbage-collected/cleaned up for me on, say, a restart – or more importantly crash – of my computer… maybe if we could change the location of it to give users full control or something, if that's not too granular/specific of a request.

Also, rather than "remove the temp files when the video is discarded," maybe only when Kap exits would be better? (or, would for me…) This could be a good middle ground between 'on video discard' and 'on computer restart.'
