### ISSUE TITLE
revisiting FPS 

### ISSUE THREAD

**Issue by gotjoshua** [wulkano/kap#792]
I can see that the FPS issue has gone through a fair bit of processing over the years (#32, #117,  #371, #418, #453, #656, #680 ...  )

If I understand the evolution correctly, there was even a time when there was 15fps as a low frame rate option, but now there is only 30 or 60...

Is there a technical reason that it is difficult to capture less frames? or was this a decision to try to simplify the UI?

I would like to repeat and clarify my (pre)proposal from #453:

1.  More options for capturing less frames during the recording phase  
(not millions, just a couple more... )   
 like 10,15,30,60 would be fine:
![FPSoptions-general-settings](https://user-images.githubusercontent.com/8686454/73882427-f0f37e00-4859-11ea-932c-268e3352ba49.png)

2. The possibility to export at up to 2x the frame rate   
(and to set a preferred default in general preferences)  
(but not by adding more frames - by setting the frame duration)

3. Visibility of the fps of the recording fps, the playback fps, and the multiplier in the export gui bottom bar.

Plugin vs core:

I can see that 2. can be easily handled by a plugin that controls ffmpeg settings, 
and maybe if you offer space in the bottom bar to plugin generated jsx (as is being discussed) then 3. could also be covered by a plugin.
I assume that plugins could also have their own preferences tab, so the options could also be added in that way.

BUT, I don't see why. It just feels like a very basic core functionality of a screen capture program to offer more than 2 options for frame rate and to allow for playback frame rates at least 2x the capture rate.

Maybe I missed some of the old discussions, or maybe I am just stubborn and demanding ; ) but I'd really love to understand the current status, and I'd also love to get coherent with the project leaders (either to surrender my opinion because you already thought it through and convince me that these features are superfluous and/or belong in a plugin.... OR more hopefully coherent in the way that we can craft a feature proposal that I can offer a PR to solve)

**Comment by skllcrn** [comment]
Thank you for the detailed issue @gotjoshua! 

1. We reasoned that we would always prefer to *capture* at the highest possible quality, which gives you more wiggle room in post. However, not all hardware is capable of capturing as many as 60 frames per second, so we defaulted to 30. After recording we let you set a custom FPS for the export, which is remembered, so if you always want to export at 15 FPS, you can set it once and leave it. It'd be great to hear your use case for capturing at a lower FPS.

2. Kind of relates to #453, being able to change the playback speed – which benefits from having a higher quality source as mentioned in 1. This is indeed something that a more advanced plugin system could allow for, maybe by passing `ffmpeg` options @karaggeorge? 

3. These are features that we have talked about but, but decided not to implement in order to focus on the core experience. I'd recommend opening separate issues for each feature request so we can gauge the interest and discuss potential solutions for each.

**Comment by gotjoshua** [comment]
Cool, thanks for the props @skllcrn !

So use case:
I want small file size gifs that only have 5-15 fps of data and are set to play faster than they were recorded (1.2x-2x)
This is for quick little examples of UI interaction.
Example:
I record 10 seconds of UI interactions at 10fps
I export a gif that will play all 100 frames in 7.5 seconds (at 1.5x) [by setting a frame delay of 0.06s](https://graphicdesign.stackexchange.com/a/121029)

I guess its also possible to record at 30 or 60 drop 60-90% of the frames until you have 10fps of data left and then set the playback to 15fps. I am not so familiar with ffmpeg options, but i guess all this is possible via post processing. 

However, I think that it fits better to adapt the core ui (very slightly) to include the possibility to change playback fps in a way that results in faster or slower playback.

**Comment by skllcrn** [comment]
I understand, right now your best option is to capture a 60 FPS recording and use the Save Orginal feature in the File menu, then edit the playback speed in a third party tool. We'll consider supporting this in #453, and I'll be closing this issue on favour of that one. Thank you!

![image](https://user-images.githubusercontent.com/8440026/74609306-3a10c100-50e9-11ea-8c8f-7a66b7ddcc24.png)
