### ISSUE TITLE
Plugins unavailable.

### ISSUE THREAD

**Issue by EnjoyColin** [wulkano/kap#811]
**macOS version:**10.15.3
**Kap version:**3.1.0

#### Workaround

<img width="548" alt="截屏2020-03-18上午12 52 18" src="https://user-images.githubusercontent.com/17642707/76880612-e265a100-68b2-11ea-808e-2694b875594c.png">

I don't know why these plugins are unavailable. There's no more alert. Maybe I missed something?

**Comment by karaggeorge** [comment]
Hey @EnjoyColin , 

these plugins will be available soon. They are disabled because they require Kap version 3.2.0 which hasn't been released yet. We are working on finalizing it. Once that is out and your app is updated, you'll be able to install and use them. 

If you want to test them in the meantime and maybe provide some feedback, feel free to download and use [this test build](https://1528-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg)

**Comment by karaggeorge** [comment]
Maybe we should do a better job at showing why a plugin can't be installed? Or even hide the ones that don't apply to the current version? 

cc @skllcrn @sindresorhus

**Comment by skllcrn** [comment]
I think hiding the ones that do not apply makes sense.

**Comment by sindresorhus** [comment]
If we hide them, people will also be confused why they see a plugin on GitHub, but it doesn’t show up in Kap. I would just add a note (box) under the app description “Requires Kap 3.2.1” and also reduce the opacity for such plugins. Maybe also sort them last.

**Comment by skllcrn** [comment]
I figured that since the client auto updates, and this is mostly due to the introduction of the new plugin system, we could get away with not adding anything to handle it. I agree though, your suggestion sounds like a good way to go about it.
