### ISSUE TITLE
Save file doesn't show in 'Kaptures' desktop folder 

### ISSUE THREAD

**Issue by Newburied** [wulkano/kap#812]
**macOS version:** 10.15.3
**Kap version:** 3.0.1

#### Steps to reproduce 

Open Kap 
Record ~10 second clip with screen record
Export to 'Kaptures' desktop folder
Kaptures folder is empty even after 'export completed'
???

#### Current behaviour
Open Kap 
Record ~10 second clip with screen record
Export to 'Kaptures' desktop folder
Kaptures folder is empty even after 'export completed'
???

I can open Kap, click the "..."settings and select 'Open Video' and it will show my recordings in the 'Kaptures' folder on my desktop but when I go to my actual desktop folder and open it it's empty

<img width="1280" alt="Screen Shot 2020-03-23 at 11 36 38 AM" src="https://user-images.githubusercontent.com/62558248/77333984-95daf500-6cfa-11ea-9107-0aa35b67d83f.png">

On the bottom left is the Kaptures folder opened through "Open Video" in the settings portion of Kap, on the bottom right is the folder opened from my desktop. 

Help pls am newb 

#### Expected behaviour
Open Kap
Record ~10 second clip with screen record
Export to 'Kaptures' desktop folder
Kapture folder shows recording

**Comment by karaggeorge** [comment]
Hey @Newburied ,

the folder that Kap saves the recordings is Kaptures under `Movies`, not `Desktop`. You can see the path in the file info window you have opened. That's why your other folder is empty. There's two folders with the same name. Kap is using the one under Movies. If you want to change where they are saved to, you can go to Preferences, and all the way to the bottom you can select your Desktop Kaptures folder if that's more convenient for you.

Let me know if you have any further troubles with this.

**Comment by Newburied** [comment]
I actually had gone through and selected the desktop folder multiple times and continued to have problems. 🤷🏻‍♂️

**Comment by karaggeorge** [comment]
Kap also saves the last saved directory. So, if you used the original one, then when you use the Save to disk option it will default to that one for the current run. If you have changed the directory to the Desktop one in the Preferences, can you restart the app and trying saving to disk again?
