### ISSUE TITLE
Don't start auto-playing after stopping recording

### ISSUE THREAD

**Issue by frozenpandaman** [wulkano/Kap#853]
Not much more to say besides the issue title – it'd be nice to have this option. I'd rather manually press play to begin previewing/watching from the start of my recording (especially if it involves audio) instead of it starting automatically.

**Comment by skllcrn** [comment]
Thank you for the feedback @frozenpandaman. Personally I think it's great to get immediate feedback once the recording has been completed, and we do pause the playback if the window is blurred. Will leave this open for a bit to gauge the interest.

**Comment by karaggeorge** [comment]
I think we pause when we blur, but we play the video once it's done loading. So if you have the editor immediately out of focus, when the preview loads it'll play and because you are not actually blurring it again until you focus it, it'll keep playing.

I think we can check when the preview is loaded if the window is currently focused or not and decide whether to play or not
